apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver2
  template:
    metadata:
      labels:
        app: webserver2
    spec:
      containers:
        - name: webserver2
          image: patakib/webserver2:latest
          ports:
            - containerPort: 8080