apiVersion: v1
kind: Service
metadata:
  name: webserver2-service
spec:
  type: NodePort
  selector:
    app: webserver2                 # Matches Deployment 2's label
  ports:
    - protocol: TCP
      port: 80                      # The Service's internal cluster port
      targetPort: 8080              # The target port in the Pod/Container
      nodePort: 30082               # Matches the second containerPort in kind-config.ya