apiVersion: v1
kind: Service
metadata:
  name: webserver1-service
spec:
  type: NodePort
  selector:
    app: webserver1                 # Matches Deployment 1's label
  ports:
    - protocol: TCP
      port: 80                      # The Service's internal cluster port
      targetPort: 8080              # The target port in the Pod/Container
      nodePort: 30081